In [8]:
import numpy as np

In [9]:
#attributes of numpy
arr = np.array((1,2)) 
print(arr)

[1 2]


In [10]:
# attributes of numpy

arr = np.array(((1, 2), (3, "ABC")))   # value, datatype

print(arr)

print(arr.ndim)
print(arr.shape)
print(type(arr))
print(arr.dtype)

[['1' '2']
 ['3' 'ABC']]
2
(2, 2)
<class 'numpy.ndarray'>
<U21


In [13]:
#method
arr = np.array(((1, 2), (3, "ABC")))   # value, datatype
print(arr)

print(np.arange(3)) 
print(np.random.rand(1,2))


[['1' '2']
 ['3' 'ABC']]
[0 1 2]
[[0.53533947 0.89204837]]


In [ ]:
#create a gusseing game where user will enter a number you have to tell number is big or small
#loop user will enter another number make it untill user guess the number
#add num, subs num

In [15]:
num = np.random.randint(0,10)
user = int(input("enter a number :"))
while(num != user):
    user = int(input("enter a number :"))
    if (num == user):
        print("you won")
    elif(num>user):
        print("guess a large number")
    else:
        print("guess a small number ")




guess a small number 


ValueError: invalid literal for int() with base 10: ''

In [16]:
#zeros
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
arr = np.random.randint(1,10,12)
print(arr)
print(arr.shape)
print(arr.reshape(3,4))
print(arr)

[1 2 7 4 5 2 3 7 1 4 4 3]
(12,)
[[1 2 7 4]
 [5 2 3 7]
 [1 4 4 3]]
[1 2 7 4 5 2 3 7 1 4 4 3]


In [ ]:
arr+arr #opt overloading

array([ 2,  4, 14,  8, 10,  4,  6, 14,  2,  8,  8,  6], dtype=int32)

In [23]:
list1 = [1,2,3,4]
list1+list1

[1, 2, 3, 4, 1, 2, 3, 4]

In [31]:
#max,min,argmax,argmin
print(arr)
max(arr)
arr.max()
max(list1)

arr.min()
arr.argmax()
arr.argmin()
arr.mean()
arr.std()


[1 2 7 4 5 2 3 7 1 4 4 3]


np.float64(1.9346977943739836)

In [32]:
arr[3] #indexing
arr[1:5] #slicing


array([2, 7, 4, 5], dtype=int32)

In [33]:
np.flip(arr)

array([3, 4, 4, 1, 7, 3, 2, 5, 4, 7, 2, 1], dtype=int32)

In [ ]:
np.arange(1,30,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [40]:
arr =  arr.reshape(3,5)